name: Build and Test SRLinker

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install MinGW64
      run: |
        choco install mingw -y
        $env:Path += ";C:\tools\mingw64\bin"

    - name: Build project with gcc
      run: |
        gcc -o SRLinker.exe main.c Root.c Actions/Backup.c Actions/AuxiliaryFunctions.c Actions/DeviceInfos.c Logo/Logo.c
  
